### Listar administradores
GET http://localhost:8080/admin HTTP/1.1

### Buscar administrador por ID 
GET http://localhost:8080/admin/1 HTTP/1.1

### Buscar administrador por E-mail
GET http://localhost:8080/admin/buscar?email=guilherme@teste.com HTTP/1.1

### Criar administrador
POST http://localhost:8080/admin HTTP/1.1
Content-Type: application/json

{
    "nome": "Guilherme Rocha",
    "email": "guilherme2@teste.com",
    "senha": "123456",
    "ativo": true,
    "nivelAcesso": "ADMIN_COMUM"
}

### Atualizar administrador
PUT http://localhost:8080/admin/4 HTTP/1.1
Content-Type: application/json

{
    "nome": "Guilherme Rocha Atualizado",
    "email": "guilherme2@teste.com",
    "senha": "123456",
    "ativo": true,
    "nivelAcesso": "ADMIN_MASTER"
}

### Deletar administrador 
DELETE http://localhost:8080/admin/5 HTTP/1.1