
### Listar administradores
GET http://localhost:8080/admin

### Buscar administrador por ID
GET http://localhost:8080/admin/1

### Buscar administrador por e-mail
GET http://localhost:8080/admin/buscar/email?email=guilherme@teste.com

### Buscar administradores por nome
GET http://localhost:8080/admin/buscar/nome?nome=gui

### Criar administrador
POST http://localhost:8080/admin
Content-Type: application/json

{
    "nome": "Guilherme Rocha",
    "email": "guilherme3@teste.com",
    "senha": "Teste@12"
}

### Atualizar administrador
PUT http://localhost:8080/admin/1
Content-Type: application/json

{
    "nome": "Guilherme Rocha Atualizado",
    "email": "guilherme@teste.com",
    "senha": "Teste@12"
}

### Deletar administrador
DELETE http://localhost:8080/admin/2
